// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxt+nitro-server@4.2.0_db0@0.3.4_ioredis@5.8.2_magicast@0.5.1_nuxt@4.2.0_@parcel+watc_6e6907b80ed135e13d6cd4f13ecee97d/node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
    '/api/_nuxt_icon/:collection': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxt+icon@2.1.0_magicast@0.5.1_vite@7.1.12_jiti@2.6.1_lightningcss@1.30.2_terser@5.44._522557b5fee258fc974d8ceea19f66c2/node_modules/@nuxt/icon/dist/runtime/server/api').default>>>>
    }
  }
}
export {}